name: bizhunt
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  build_runner: ^2.4.13
  mockito: ^5.4.4
  flutter_rating_bar: ^4.0.1
  animation_search_bar: ^0.0.10
  cached_network_image: ^3.4.1
  loading_indicator: ^3.1.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
